# This is an example configuration file for the server
# Rename this file to config.toml to use it

[static_message]
send = true 
message = 'Hello, World!' 

[chat]
enabled = true

[server]
port = '8080'
